name: scopa_lib
description: A library to manage and play a game of Scopa.
version: 1.0.0-indev
repository: https://github.com/mnowakowski98/scopa_lib

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
